### ISSUE TITLE
Add customization for Audience's emails

### ISSUE THREAD

**Issue by kjanoudi** [LeadGrabr/api#26]
Add fields for the different types of emails and their configurations:
- Lead thank you email image 
- Header image for client confirmation email

OR
-  Maybe just allow them to design the email template itself and upload it to S3? @bentatum

**Comment by rawgroundbeef** [comment]
Let's give them a basic outline that can be overridden with a custom template. @kjanoudi

**Comment by kjanoudi** [comment]
#29
